apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: goku-replset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: gokulakrishna/docker-training
