apiVersion: v1
kind: ReplicationController
metadata:
  name: goku-rc
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: gokulakrishna/docker-training
        ports:
        - containerPort: 8080
